- name: disabling mysql module 8 version
  ansible.builtin.command: dnf module disable mysql -y

- name: setting up mysql.repo
  ansible.builtin.copy:
    src: mysql.repo
    dest: /etc/yum.repos.d/mysql.repo

- name: installing mysql community server
  ansible.builtin.package: 
    name: mysql-community-server
    state: present

- name: start, enable mysql services
  ansible.builtin.service:
    name: mysqld
    state: started
    enabled: yes

- name: setting up passwd
  ansible.builtin.command: "mysql_secure_installation --set-root-pass {{ lookup('aws_ssm', '/roboshop/{{env}}/mysql_root_paas', region='us-east-1', decrypt=True ) }}"